spring:
  application:
    name: person-user-profile-api

server:
  port: 8073

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://service-registry-person.herokuapp.com/eureka/
  instance:
    hostname: service-registry-person.herokuapp.com