spring:
  application:
    name: person-user-profile-api

server:
  port: 8073

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
  instance:
    hostname: localhost